kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: krateo-core-provider
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - core.krateo.io
  resources:
  - definitions
  - definitions/status
  verbs:
  - '*'